[package]
name             = "bar-renderer"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bar-core    = { workspace = true }
bar-config  = { workspace = true }
bar-widgets = { workspace = true }
iced        = { workspace = true }
